language: php
php:
  - 7.0
  - 7.1
services:
  - mysql
branches:
  only:
    master
before_install:
  - cd server
  - travis_retry composer self-update
  - composer install
before_script: 
  - mysql -e 'CREATE DATABASE wasps;'
script: composer test